/**
 * Default genre artwork: cropped, tinted variations of the supplied venue photograph
 * (public/brand/genres, generated by `npm run brand:assets`). Used until the owner uploads a cover.
 * The choice is deterministic per genre slug, so a genre keeps the same artwork everywhere.
 */
export const DEFAULT_GENRE_ARTWORK_COUNT = 8;

export const VENUE_HERO_IMAGE = { src: "/brand/venue-hero.jpg", width: 1536, height: 1024 } as const;

/**
 * Hand-picked artwork for the common genres so the default collection never repeats an image
 * (01 amber bar, 02 gold lamps, 03 evergreen lounge, 04 night teal, 05 wine, 06 indigo seats,
 * 07 sunset cocktail, 08 olive plants). Other slugs fall back to a stable hash.
 */
const KNOWN_GENRE_ARTWORK: Record<string, number> = {
  house: 1,
  jazz: 2,
  lounge: 3,
  chillout: 4,
  "deep-house": 5,
  pop: 6,
  "balkan-hits": 7,
  rock: 8,
  "r-b": 5,
  "r-and-b": 5,
  rnb: 5,
};

export function defaultGenreArtwork(key: string): string {
  const known = KNOWN_GENRE_ARTWORK[key.toLowerCase()];
  if (known) return `/brand/genres/default-${String(known).padStart(2, "0")}.jpg`;
  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
  }
  const index = (hash % DEFAULT_GENRE_ARTWORK_COUNT) + 1;
  return `/brand/genres/default-${String(index).padStart(2, "0")}.jpg`;
}

/** Owner-uploaded cover when present, otherwise the deterministic default artwork. */
export function genreArtwork(genre: { slug: string; coverUrl?: string | null }): string {
  return genre.coverUrl ?? defaultGenreArtwork(genre.slug);
}
