// The demo catalogue shared by `npm run demo:audio` (what to synthesise) and `npm run seed:dev`
// (what to create). All demo content is clearly labelled as synthetic/example data.
import { PLATFORM_NAME } from "../../src/config/platform";
import {
  getAnnouncementTemplate,
  renderAnnouncementWording,
  type AnnouncementTemplateKey,
} from "../../src/lib/announcements/templates";
import type { BusinessTypeEnum } from "../../src/types/database";
import type { ChimeOptions, MusicStyle } from "./audio-synth";

/** Artist on every demo file: makes the synthetic origin obvious in the player and the admin UI. */
export const DEMO_ARTIST = `${PLATFORM_NAME} Test Signal`;
export const DEMO_ALBUM = `${PLATFORM_NAME} demo audio (synthetic)`;
export const SYNTHETIC_NOTICE =
  "Synthetic test audio generated by `npm run demo:audio` for development and acceptance testing. " +
  "The music files are generated tone loops, not real music; announcements are computer speech (Windows SAPI) " +
  "or chime placeholders, not recordings of a real person.";

// ---------------------------------------------------------------------------
// Genres
// ---------------------------------------------------------------------------

export interface DemoGenre {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
  /** false ⇒ only businesses with an access row (see DemoBusiness.exclusiveGenreSlugs). */
  availableToAll: boolean;
  /** Number of synthetic loops; 0 leaves the genre empty (exercises the player's "no tracks" state). */
  demoTracks: number;
  /** Synth style for the loops (null when demoTracks is 0). */
  style: MusicStyle | null;
}

const MAJOR_POP: MusicStyle["progression"] = [
  { bass: 48, notes: [60, 64, 67] }, // C
  { bass: 43, notes: [59, 62, 67] }, // G
  { bass: 45, notes: [60, 64, 69] }, // Am
  { bass: 41, notes: [60, 65, 69] }, // F
];

export const DEMO_GENRES: readonly DemoGenre[] = [
  {
    slug: "house",
    name: "House",
    description: "Four-on-the-floor grooves for busy evenings.",
    sortOrder: 1,
    availableToAll: true,
    demoTracks: 6,
    style: {
      mood: "bright",
      bpm: 122,
      key: 0,
      progression: MAJOR_POP,
      kick: "four-on-the-floor",
      hats: "offbeat",
      bass: "offbeat",
      arpeggio: "eighths",
      chordStabs: false,
      timbre: {
        padHarmonics: [1, 0.3, 0.12],
        padLevel: 0.06,
        padAttackSeconds: 0.3,
        pluckHarmonics: [1, 0.45, 0.2],
        pluckLevel: 0.06,
        pluckDecaySeconds: 0.14,
      },
    },
  },
  {
    slug: "deep-house",
    name: "Deep House",
    description: "Warm late-night house with deeper chords.",
    sortOrder: 2,
    availableToAll: true,
    demoTracks: 3,
    style: {
      mood: "deep",
      bpm: 118,
      key: -3,
      progression: [
        { bass: 48, notes: [63, 67, 70, 74] }, // Cm9
        { bass: 44, notes: [63, 67, 68, 72] }, // Abmaj7
        { bass: 41, notes: [63, 65, 68, 72] }, // Fm7
        { bass: 46, notes: [62, 65, 70, 72] }, // Bbadd9
      ],
      kick: "four-on-the-floor",
      hats: "shaker",
      bass: "pulse",
      arpeggio: "sixteenths",
      chordStabs: false,
      timbre: {
        padHarmonics: [1, 0.15, 0.04],
        padLevel: 0.075,
        padAttackSeconds: 0.5,
        pluckHarmonics: [1, 0.25],
        pluckLevel: 0.045,
        pluckDecaySeconds: 0.1,
      },
    },
  },
  {
    slug: "lounge",
    name: "Lounge",
    description: "Relaxed background music for dining and conversation.",
    sortOrder: 3,
    availableToAll: true,
    demoTracks: 4,
    style: {
      mood: "warm",
      bpm: 92,
      key: 2,
      progression: [
        { bass: 48, notes: [60, 64, 67, 71] }, // Cmaj7
        { bass: 45, notes: [60, 64, 67, 69] }, // Am7
        { bass: 50, notes: [62, 65, 69, 72] }, // Dm7
        { bass: 43, notes: [59, 62, 65, 67] }, // G7
      ],
      kick: "half-time",
      hats: "offbeat",
      bass: "pulse",
      arpeggio: "eighths",
      chordStabs: false,
      timbre: {
        padHarmonics: [1, 0.25, 0.08],
        padLevel: 0.065,
        padAttackSeconds: 0.35,
        pluckHarmonics: [1, 0.5, 0.12, 0.05],
        pluckLevel: 0.055,
        pluckDecaySeconds: 0.3,
      },
    },
  },
  {
    slug: "jazz",
    name: "Jazz",
    description: "Smooth, swinging jazz for lobbies and bars.",
    sortOrder: 4,
    availableToAll: false,
    demoTracks: 3,
    style: {
      mood: "smoky",
      bpm: 104,
      key: -2,
      progression: [
        { bass: 50, notes: [65, 69, 72, 76] }, // Dm9 (rootless)
        { bass: 43, notes: [65, 69, 71, 76] }, // G13 (rootless)
        { bass: 48, notes: [64, 67, 71, 74] }, // Cmaj9 (rootless)
        { bass: 45, notes: [61, 65, 67, 71] }, // A7(b13)
      ],
      kick: "none",
      hats: "swing-ride",
      bass: "walking",
      arpeggio: "swing-eighths",
      chordStabs: false,
      timbre: {
        padHarmonics: [1, 0.2, 0.05],
        padLevel: 0.05,
        padAttackSeconds: 0.2,
        pluckHarmonics: [1, 0, 0, 0.3],
        pluckLevel: 0.045,
        pluckDecaySeconds: 0.35,
      },
    },
  },
  {
    slug: "pop",
    name: "Pop",
    description: "Familiar, upbeat pop.",
    sortOrder: 5,
    availableToAll: true,
    demoTracks: 0,
    style: null,
  },
  {
    slug: "rock",
    name: "Rock",
    description: "Guitar-driven classics.",
    sortOrder: 6,
    availableToAll: true,
    demoTracks: 0,
    style: null,
  },
  {
    slug: "rnb",
    name: "R&B",
    description: "Smooth rhythm and blues.",
    sortOrder: 7,
    availableToAll: true,
    demoTracks: 0,
    style: null,
  },
  {
    slug: "balkan-hits",
    name: "Balkan Hits",
    description: "Energetic Balkan party favourites.",
    sortOrder: 8,
    availableToAll: false,
    demoTracks: 2,
    style: {
      mood: "festive",
      bpm: 132,
      key: 2,
      progression: [
        { bass: 48, notes: [60, 63, 67] }, // Cm
        { bass: 41, notes: [60, 65, 68] }, // Fm
        { bass: 43, notes: [59, 62, 65, 67] }, // G7 (harmonic minor)
        { bass: 48, notes: [60, 63, 67] }, // Cm
      ],
      kick: "half-time",
      hats: "offbeat",
      bass: "oom-pah",
      arpeggio: "eighths",
      chordStabs: true,
      timbre: {
        padHarmonics: [1, 0.3, 0.1],
        padLevel: 0.04,
        padAttackSeconds: 0.15,
        pluckHarmonics: [1, 0.5, 0.3, 0.1],
        pluckLevel: 0.05,
        pluckDecaySeconds: 0.1,
      },
    },
  },
  {
    slug: "chillout",
    name: "Chillout",
    description: "Airy downtempo for quiet hours.",
    sortOrder: 9,
    availableToAll: true,
    demoTracks: 3,
    style: {
      mood: "airy",
      bpm: 84,
      key: 5,
      progression: [
        { bass: 48, notes: [64, 67, 71, 74] }, // Cmaj9
        { bass: 40, notes: [62, 64, 67, 71] }, // Em7
        { bass: 41, notes: [60, 64, 65, 69] }, // Fmaj7
        { bass: 43, notes: [60, 62, 67] }, // Gsus4
      ],
      kick: "none",
      hats: "none",
      bass: "sustained",
      arpeggio: "eighths",
      chordStabs: false,
      timbre: {
        padHarmonics: [1, 0.1, 0.05],
        padLevel: 0.075,
        padAttackSeconds: 1.2,
        pluckHarmonics: [1, 0.3, 0, 0.1],
        pluckLevel: 0.035,
        pluckDecaySeconds: 0.45,
      },
    },
  },
];

// ---------------------------------------------------------------------------
// Businesses, users and announcements
// ---------------------------------------------------------------------------

export type DemoBusinessKey = "emeraldbar" | "hotel-aurora";

/** Same wording as the admin's business type labels (src/components/admin/businesses/business-form.ts). */
const BUSINESS_TYPE_LABELS: Readonly<Record<BusinessTypeEnum, string>> = {
  cafe: "Café",
  restaurant: "Restaurant",
  hotel: "Hotel",
  bar: "Bar",
  other: "Other",
};

/** "Bar", "Hotel", …; for console output. */
export function businessTypeLabel(type: BusinessTypeEnum): string {
  return BUSINESS_TYPE_LABELS[type] ?? type;
}

export interface DemoUserDefinition {
  /** Environment variable that overrides the email. */
  envVar: string;
  defaultEmail: string;
  fullName: string;
}

export interface DemoBusiness {
  key: DemoBusinessKey;
  /** The names the spec and the demo announcements use; they stay exactly as written (no "(example)"). */
  name: string;
  stationName: string;
  namePronunciation: string | null;
  stationNamePronunciation: string | null;
  /** businesses.business_type, shown under the name in the admin list and on the venue's Account page. */
  businessType: BusinessTypeEnum;
  /**
   * Seed marker: an example.com address that labels the row as demo data. It is the venue's visible
   * "Contact email" in the admin, and searching the business list for "example.com" finds the demo
   * venues (the businesses table has no notes column to carry an "example" label). The seed only ever
   * reuses a business whose name AND contact email match, so it never touches a real venue with the
   * same name. The announcement frequency is not set here: new demo venues get the platform default
   * (platform_settings.default_announcement_every_n_tracks), like venues added in the admin.
   */
  contactEmail: string;
  /** Genres with available_to_all = false that this venue gets an access row for. */
  exclusiveGenreSlugs: string[];
  /** Preferred Windows SAPI voice for the demo announcements. */
  sapiVoice: string;
  /** Placeholder melody when SAPI is unavailable (distinct per business). */
  chime: Pick<ChimeOptions, "notesHz" | "timbre">;
  user: DemoUserDefinition;
}

export const DEMO_BUSINESSES: readonly DemoBusiness[] = [
  {
    key: "emeraldbar",
    name: "EmeraldBar",
    stationName: "EmeraldBar Radio",
    namePronunciation: "Emerald Bar",
    stationNamePronunciation: null,
    businessType: "bar",
    contactEmail: "demo+emeraldbar@example.com",
    exclusiveGenreSlugs: ["balkan-hits"],
    sapiVoice: "Microsoft David Desktop",
    chime: { notesHz: [659.26, 783.99, 987.77, 1318.51], timbre: "bell" }, // E5 G5 B5 E6, rising
    user: { envVar: "SEED_EMERALDBAR_EMAIL", defaultEmail: "emeraldbar@example.com", fullName: "EmeraldBar demo user" },
  },
  {
    key: "hotel-aurora",
    name: "Hotel Aurora",
    stationName: "Hotel Aurora Radio",
    namePronunciation: null,
    stationNamePronunciation: null,
    businessType: "hotel",
    contactEmail: "demo+hotel-aurora@example.com",
    exclusiveGenreSlugs: ["jazz"],
    sapiVoice: "Microsoft Zira Desktop",
    chime: { notesHz: [1046.5, 880, 698.46, 523.25], timbre: "marimba" }, // C6 A5 F5 C5, falling
    user: { envVar: "SEED_AURORA_EMAIL", defaultEmail: "hotel-aurora@example.com", fullName: "Hotel Aurora demo user" },
  },
];

export const DEMO_ADMIN: DemoUserDefinition = {
  envVar: "SEED_ADMIN_EMAIL",
  defaultEmail: "admin@example.com",
  fullName: "Demo platform admin",
};

/** Keys from ANNOUNCEMENT_TEMPLATES (src/lib/announcements/templates.ts), in playback-relevant order. */
export const DEMO_ANNOUNCEMENT_TEMPLATE_KEYS: readonly AnnouncementTemplateKey[] = ["welcome_enjoy", "station_listening", "good_music"];

export interface DemoAnnouncement {
  /** Stable file id, e.g. "emeraldbar-welcome-enjoy". */
  id: string;
  businessKey: DemoBusinessKey;
  templateKey: AnnouncementTemplateKey;
  /** Human label of the template, e.g. "Welcome". */
  label: string;
  placement: "welcome" | "rotation" | "both";
  /** Display wording with the real names. */
  text: string;
  /** Wording with pronunciation spellings, or null when identical to `text`. */
  spokenText: string | null;
  /** Placeholder melody for this announcement (distinct per business and per announcement). */
  chime: ChimeOptions;
}

/** The chime variant for the n-th announcement of a business: 4 rising/falling notes, the first 2, or 3 reversed. */
function chimeVariant(business: DemoBusiness, index: number): ChimeOptions {
  const notes = business.chime.notesHz;
  const variants = [notes, notes.slice(0, 2), [...notes.slice(0, 3)].reverse()];
  return { notesHz: variants[index % variants.length], timbre: business.chime.timbre, spacingSeconds: 0.32 };
}

export function demoAnnouncementsFor(business: DemoBusiness): DemoAnnouncement[] {
  return DEMO_ANNOUNCEMENT_TEMPLATE_KEYS.map((templateKey, index) => {
    const template = getAnnouncementTemplate(templateKey);
    if (!template) throw new Error(`Announcement template "${templateKey}" does not exist in src/lib/announcements/templates.ts`);
    const wording = renderAnnouncementWording(template.text, business);
    return {
      id: `${business.key}-${templateKey.replace(/_/g, "-")}`,
      businessKey: business.key,
      templateKey,
      label: template.label,
      placement: template.defaultPlacement,
      text: wording.text,
      spokenText: wording.spokenText,
      chime: chimeVariant(business, index),
    };
  });
}

export function findDemoBusiness(key: string): DemoBusiness | undefined {
  return DEMO_BUSINESSES.find((business) => business.key === key);
}

export function findDemoGenre(slug: string): DemoGenre | undefined {
  return DEMO_GENRES.find((genre) => genre.slug === slug);
}

// ---------------------------------------------------------------------------
// Demo tracks
// ---------------------------------------------------------------------------

export interface DemoTrack {
  /** 1-based position across all genres (the number in the title). */
  number: number;
  /** Stable file id, e.g. "test-loop-01-house". */
  id: string;
  title: string;
  genre: DemoGenre & { style: MusicStyle };
  /** Deterministic synth seed. */
  seed: number;
  /** Target length, 21–38 s; the synth rounds it to whole bars, so files are 20–40 s long. */
  targetSeconds: number;
}

/** Every demo loop, numbered 01…N across the genres in sort order. */
export function listDemoTracks(): DemoTrack[] {
  const tracks: DemoTrack[] = [];
  for (const genre of DEMO_GENRES) {
    const style = genre.style;
    if (genre.demoTracks === 0) continue;
    if (!style) throw new Error(`Genre "${genre.slug}" has demo tracks but no synth style`);
    for (let k = 0; k < genre.demoTracks; k++) {
      const number = tracks.length + 1;
      const padded = String(number).padStart(2, "0");
      tracks.push({
        number,
        id: `test-loop-${padded}-${genre.slug}`,
        title: `Test Loop ${padded} — ${genre.name} (synthetic)`,
        genre: { ...genre, style },
        seed: number * 7919,
        // Short loops so "announcement after every 4 completed tracks" can be tested in minutes.
        targetSeconds: 21 + ((number * 11) % 18),
      });
    }
  }
  return tracks;
}
